version: '3'


services:

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - telecom
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ../api
    networks:
      - telecom
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      - DATABASE_NAME=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

volumes:
  web-django:
  web-static:
  pgdata:

networks:
  telecom: