name: Python Linting
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.1
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.1.12-0

      - run: poetry install --no-interaction --no-root
        working-directory: ./api

      - name: Run black
        working-directory: ./api
        run: |
          poetry run black --check .

      - name: Run isort
        working-directory: ./api
        run: |
          poetry run isort -c .
